resources:
  - url: /local/custom_cards/custom-cards.js?v=1.106
    type: module
  - url: /community_plugin/canvas-gauge-card/canvas-gauge-card.js?v=0.0.21
    type: module
  # - url: /local/custom_cards/mini-graph-card-bundle.js?v=0.2.4
  #   type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js?v=0.0.1
    type: module
  # - url: /local/custom_cards/smhi-forecast-card.js?v=0.0.26
  #   type: module
  - url: /community_plugin/krisinfo-card/krisinfo-card.js
    type: js
  # - url: /community_plugin/weather-card/weather-card.js?v1.0
  #   type: js
  - url: /community_plugin/weather-card-mod/weather-card-mod.js?v0.5
    type: module
  # - url: /local/custom_cards/card-tools.js?v1.1
  #   type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: js

title: Hellströms home
views:
  - !include lovelace/home.yaml
  - !include lovelace/cast.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/car.yaml
  - !include lovelace/presence.yaml
  - !include lovelace/system.yaml
  - !include lovelace/cameras.yaml
  # - cards:
  #     - camera_image: camera.kamera_uppe
  #       entities:
  #         - sensor.kamera_uppe_light_sensor
  #         - switch.kamera_uppe_night_mode
  #         - binary_sensor.kamera_uppe_motion_sensor
  #       id: fbe940e9094c458b9083ff0d3450b38f
  #       type: picture-glance
  #     - entities:
  #         - camera.kamera_uppe
  #         - switch.kamera_uppe_h264_rtsp_server
  #         - switch.kamera_uppe_mjpeg_rtsp_server
  #         - sensor.kamera_uppe
  #         - device_tracker.kamera_uppe
  #         - sensor.kamera_uppe_light_sensor
  #         - switch.kamera_uppe_ir_filter
  #         - switch.kamera_uppe_ir_led
  #         - switch.kamera_uppe_night_mode
  #         - switch.kamera_uppe_night_mode_auto
  #         - switch.kamera_uppe_blue_led
  #         - switch.kamera_uppe_yellow_led
  #         - switch.kamera_uppe_motion_detection
  #         - switch.kamera_uppe_motion_tracking
  #         - camera.kamera_uppe_motion_snapshot
  #         - binary_sensor.kamera_uppe_motion_sensor
  #       id: bfade4e5c6fb4af89cfc159f5731482e
  #       type: entities
  #   icon: 'mdi:camera'
  #   id: 6
  #   title: Kameror
