site_name: My Home Assistant docs
theme: 'material' #readthedocs
google_analytics:
  - UA-133997912-1
  - auto
repo_url: https://github.com/helto4real/hassio/
site_dir: site
site_author: 'Tomas Hellström, @helto4real'