group:
  low_battery_devices:
    name: Batteristat
    entities:
      -
  people_status:
    name: Familjen hemmastatus
    entities:
      - device_tracker.elin_presence
      - device_tracker.tomas_presence
      - device_tracker.melker_presence
      - device_tracker.sally_presence

  presence:
    name: Familjens devicestatus
    icon: mdi:home-account
    entities:
      - group.tomas_devices
      - group.elins_devices
      - group.sallys_devices
      - group.melkers_devices

  tomas_devices:
    name: Tomas trackers
    entities:
      # - sensor.tomas_phone_mqtt_bt #Bluetooth
      - device_tracker.google_maps_118123190245690142371 #Gps
      - device_tracker.tomas_galaxy_wifi # wifi

  elins_devices:
    name: Elin trackers
    entities:
      # - sensor.elin_phone_mqtt_bt #BT
      - device_tracker.google_maps_110786808112177763666 #Gps
      - device_tracker.elin_galaxy_wifi #wifi

  melkers_devices:
    name: Melkers trackers
    entities:
      - device_tracker.google_maps_113728439587103002947
      # - sensor.melker_phone_mqtt_bt
      - device_tracker.melker_huawei_wifi

  sallys_devices:
    name: Sallys trackers
    entities:
      - device_tracker.sally_huawei_wifi
      # - sensor.sally_phone_mqtt_bt
      - device_tracker.google_maps_115932713534918928318

automation:
  - alias: Send message on away-home notice Tomas
    trigger:
      - platform: state
        entity_id: sensor.tomas_presence
    condition:
      - condition: template
        value_template: "{{ trigger.from_state != None and trigger.from_state.state != trigger.to_state.state }}"
    action:
      service: script.notify_greet
      data_template:
        person: Tomas
        title: "Tomas status {{trigger.to_state.state}}"
        message: "Tomas har ändrat tracking status från state {{trigger.from_state.state}} till state {{trigger.to_state.state}}!"

# For aproximity
proximity:
  prox_home_elin:
    ignored_zones:
      - sjukhuset
    devices:
      - device_tracker.elin_presence
    tolerance: 50
  prox_home_tomas:
    ignored_zones:
      - spv
    devices:
      - device_tracker.tomas_presence
    tolerance: 50

  prox_home_melker:
    ignored_zones:
      - matfors_skola
    devices:
      - device_tracker.melker_presence
    tolerance: 50

  prox_home_sally:
    ignored_zones:
      - skvaderns_skola
    devices:
      - device_tracker.sally_presence
    tolerance: 50

# unifi:
#   controllers:
#     - host: !secret unifi_host
#       site: HEMMA
#       ssid_filter:
#         - !secret unifi_SSID

# For tracking
# device_tracker:
#   - platform: unifi
#     host: !secret unifi_host
#     username: !secret unifi_username
#     password: !secret unifi_password
#     detection_time: 120
#     verify_ssl: false
#     ssid_filter:
#       - !secret unifi_SSID
device_tracker:
  - platform: google_maps
    username: !secret gu
  # - platform: bluetooth_tracker
  # password: !secret gp
  # - platform: googlehome
  #   host: '192.168.1.65'
# sensor:
#   - platform: mqtt
#     name: tomas_phone_mqtt_bt
#     state_topic: "test/bluetooth/owner/house/A0:10:81:18:E9:AD"
#     value_template: >
#       {% if float(value_json.confidence) > 0 %}
#        home
#       {% else %}
#        not_home
#       {% endif %}
#     json_attributes:
#       - "confidence"

#   - platform: mqtt
#     name: elin_phone_mqtt_bt
#     state_topic: "test/bluetooth/owner/house/48:27:EA:3E:9F:8F"
#     value_template: >
#       {% if float(value_json.confidence) > 0 %}
#        home
#       {% else %}
#        not_home
#       {% endif %}
#     json_attributes:
#       - "confidence"

#   - platform: mqtt
#     name: melker_phone_mqtt_bt
#     state_topic: "test/bluetooth/owner/house/F8:E6:1A:9A:5C:86"
#     value_template: >
#       {% if float(value_json.confidence) > 0 %}
#        home
#       {% else %}
#        not_home
#       {% endif %}
#     json_attributes:
#       - "confidence"

#   - platform: mqtt
#     name: sally_phone_mqtt_bt
#     state_topic: "test/bluetooth/owner/house/A0:57:E3:15:DE:4E"
#     value_template: >
#       {% if float(value_json.confidence) > 0 %}
#        home
#       {% else %}
#        not_home
#       {% endif %}
#     json_attributes:
#       - "confidence"
