

# Track the sun
sun:

# Weather prediction
sensor:
#  - platform: yr # Wheather
#    monitored_conditions:
#      - temperature
#      - symbol
#      - cloudiness
#      - windSpeed
  - platform: template
    sensors:
      temp_outside:
          friendly_name: "Temperature outside"
          value_template: "{{ states('sensor.ute_temp') | round(0) }}"
      hum_outside:
          friendly_name: "Humidity outside"
          value_template: "{{ states('sensor.ute_hum') | round(0) }}"

group:
  # För givare och väder
  climate:
    name: Klimat
    entities:
      - sensor.ute_temperature
      - sensor.hum_altan_ute
      - sun.sun
#      - sensor.yr_symbol
#      - sensor.yr_cloudiness
#      - sensor.yr_wind_speed
