esphome:
  name: esp_12_test
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

switch:
  - platform: gpio
    name: "a_diod"
    pin: GPIO5

sensor:
  - platform: adc
    name: "diod_temp"
    pin: A0
    update_interval: 5s
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1
    filters:
    - sliding_window_moving_average:
        window_size: 15
        send_every: 30
    -  lambda: return (x - 0.5) * (330/5);