esphome:
  name: shelly_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    name: "sw_input"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "shelly_relay"
    pin: GPIO4
    id: relay

