esphome:
  name: test1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

switch:
  - platform: gpio
    name: "Diod"
    pin: D1

sensor:
  - platform: adc
    name: "sound"
    pin: A0
    update_interval: 5s
    # filters:
    # -  lambda: return ((x * (3300.0/1024)) - 500) / 10;
